version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --with docs
    - poetry env info
    - sphinx-build docs _readthedocs/html

sphinx:
  configuration: docs/conf.py
