["tparser/parser"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "1.6"
build = 11
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "tparser/telegram", "packages/schedule",]
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Бот для отправки расписания уроков"
ver = "sp v1.0"
build = 5
authors = [ "Артём Березин",]
require = [ "tparser/parser",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Плагин Чио для отправки расписания уроков"
ver = "sp v1.6"
build = 5
require = [ "tparser/parser",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/parser".files]
"tparser/tparser.py" = "b88d007ad296eff62df4b956ecf4b799"
"tparser/console.py" = "e054301074e23eb231478523d2b6bbe9"
"tparser/packages.toml" = "fb84180192383c8adac107c54b5d0d31"

["tparser/telegram".files]
"tparser/telegram.py" = "2ed28ff9cdef5b1906baa8fca83a011e"
"tparser/packages.toml" = "fb84180192383c8adac107c54b5d0d31"

["packages/schedule".files]
"packages/schedule/main.py" = "0f989e6420fe471135acfd0bcfaf42b0"
"packages/schedule/packages.toml" = "2ed2d270aab1c9cb8e5b6491be8a2409"
