["tparser/parser"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "2.4.1"
build = 19
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "tparser/telegram", "packages/schedule",]
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Бот для отправки расписания уроков"
ver = "sp v1.0"
build = 5
authors = [ "Артём Березин",]
require = [ "tparser/parser",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Плагин Чио для отправки расписания уроков"
ver = "sp v2.3"
build = 10
require = [ "tparser/parser",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/parser".files]
"tparser/tparser.py" = "c1926e1781b81a016dc545a67cb23ba5"
"tparser/console.py" = "5b618937f1f9918a146322170cb12069"
"tparser/packages.toml" = "d342e0db2653cd0094fee6d4e132b6ad"

["tparser/telegram".files]
"tparser/telegram.py" = "2ed28ff9cdef5b1906baa8fca83a011e"
"tparser/packages.toml" = "d342e0db2653cd0094fee6d4e132b6ad"

["packages/schedule".files]
"packages/schedule/main.py" = "59d0b3fad5b579bc6b1380805cbb7ee5"
"packages/schedule/packages.toml" = "a70567ad7825cd718133e1b3b33976cc"
