["tparser/parser"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "1.4"
build = 6
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = []
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Telegram бот для tparser"
ver = "2.1 (SP v1.0)"
build = 5
authors = [ "Артём Березин",]
require = [ "tparser/main",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Получени школьного расписания в Чио"
ver = "1.0"
build = 1
require = [ "tparser/main",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/parser".files]
"tparser/tparser.py" = "14dfff3fc613dc0580344072cec13adb"
"tparser/console.py" = "140f7d43e24d5828eb8575004469d42e"
"tparser/packages.toml" = "55edbfb9bab795bae0543071ff0e0717"

["tparser/telegram".files]
"tparser/telegram.py" = "f7192e65f3bd906da76c4817f150576d"
"tparser/packages.toml" = "55edbfb9bab795bae0543071ff0e0717"

["packages/schedule".files]
"packages/schedule/main.py" = "2ec6cb4ca728aa1a1082cdf7862219d3"
"packages/schedule/packages.toml" = "4d763d71ad376f67fa43ff74c2627035"
