["tparser/parser"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "2.3"
build = 16
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "tparser/telegram", "packages/schedule",]
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Бот для отправки расписания уроков"
ver = "sp v1.0"
build = 5
authors = [ "Артём Березин",]
require = [ "tparser/parser",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Плагин Чио для отправки расписания уроков"
ver = "sp v2.3"
build = 10
require = [ "tparser/parser",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/parser".files]
"tparser/tparser.py" = "c5f37314e33a29daff1ae183eb51597b"
"tparser/console.py" = "d05008edf66fe74c89b75e99e2fe39ff"
"tparser/packages.toml" = "84c819c4f012648c87e6419a618b289b"

["tparser/telegram".files]
"tparser/telegram.py" = "2ed28ff9cdef5b1906baa8fca83a011e"
"tparser/packages.toml" = "84c819c4f012648c87e6419a618b289b"

["packages/schedule".files]
"packages/schedule/main.py" = "bb2f7e021251fd1fce044d1e51e4e01c"
"packages/schedule/packages.toml" = "a70567ad7825cd718133e1b3b33976cc"
