["sparser/sp"]
name = "Schedule Parser"
desc = "Парсер школьного расписания"
ver = "3.1"
build = 24
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "sparser/telegram", "packages/schedule",]
path = "./sparser"
multiple = true

["sparser/telegram"]
name = "Telegram Schedule"
desc = "[УСТАРЕЛ!] [pytelegrambotapi] Бот для отправки расписания уроков"
ver = "sp v1.0"
build = 5
authors = [ "Артём Березин",]
require = [ "sparser/sp",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./sparser"
multiple = true

["packages/schedule"]
name = "Chio Schedule"
desc = "Плагин Чио для отправки расписания уроков"
ver = "sp v3.1"
build = 12
require = [ "sparser/sp",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["sparser/sp".files]
"sparser/sparser.py" = "c5745f74061a57bbb2d4ef87eacfbbc7"
"sparser/console.py" = "1af9cc7b7377c2ba152a5cf7d5400f81"
"sparser/packages.toml" = "899fd0b83916606877d4896c9a69ca6d"

["sparser/telegram".files]
"sparser/telegram.py" = "8ca294ef5b53fd71f2279e14600d78f7"
"sparser/packages.toml" = "899fd0b83916606877d4896c9a69ca6d"

["packages/schedule".files]
"packages/schedule/main.py" = "9a3454e8fe18a5950090c5bbbdcff0b0"
"packages/schedule/packages.toml" = "1960e1b7d7166c502ade43528f04a90d"
