["tparser/main"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "1.2"
build = 4
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "tparser/telegram", "packages/schedule",]
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Telegram бот для tparser"
ver = "2.1"
build = 5
authors = [ "Артём Березин", "Milinuri Nirvalen",]
require = [ "tparser/main",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Получени школьного расписания в Чио"
ver = "1.0"
build = 1
require = [ "tparser/main",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/main".files]
"tparser/tparser.py" = "b6091dbc75f24485aaf3a1b3ae46289a"
"tparser/console.py" = "f677382619807679bd726a8b300197fd"
"tparser/packages.toml" = "0c1663b1ce8423b1e1120103acccf20e"

["tparser/telegram".files]
"tparser/telegram.py" = "7ef9736773f93e94cd8714566c638c2f"
"tparser/packages.toml" = "0c1663b1ce8423b1e1120103acccf20e"

["packages/schedule".files]
"packages/schedule/packages.toml" = "4d763d71ad376f67fa43ff74c2627035"
"packages/schedule/main.py" = "2ec6cb4ca728aa1a1082cdf7862219d3"
