["tparser/parser"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "1.4"
build = 7
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "tparser/telegram", "packages/schedule",]
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Telegram бот для tparser"
ver = "2.1 (SP v1.0)"
build = 5
authors = [ "Артём Березин",]
require = [ "tparser/parser",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Получение школьного расписания в Чио"
ver = "SP v1.4"
build = 2
require = [ "tparser/parser",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/parser".files]
"tparser/tparser.py" = "0fcb2da415de9eec922c78fae78dd160"
"tparser/console.py" = "daed6ba601328c3c79d3ae8901b5cd9d"
"tparser/packages.toml" = "410ff5095e01db686ecfba2e9ef58ac3"

["tparser/telegram".files]
"tparser/telegram.py" = "f7192e65f3bd906da76c4817f150576d"
"tparser/packages.toml" = "410ff5095e01db686ecfba2e9ef58ac3"

["packages/schedule".files]
"packages/schedule/main.py" = "b6ae4497db9472237c574fcdf3741784"
"packages/schedule/packages.toml" = "ac14fcf34f13354f0e0a70f5555fd373"
