["tparser/parser"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "2.2"
build = 15
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "tparser/telegram", "packages/schedule",]
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Бот для отправки расписания уроков"
ver = "sp v1.0"
build = 5
authors = [ "Артём Березин",]
require = [ "tparser/parser",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Плагин Чио для отправки расписания уроков"
ver = "sp v2.2"
build = 7
require = [ "tparser/parser",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/parser".files]
"tparser/tparser.py" = "b4eab2884edac4d80fe818e46e82738f"
"tparser/console.py" = "d05008edf66fe74c89b75e99e2fe39ff"
"tparser/packages.toml" = "be66af15a593176b1f495273c410ab99"

["tparser/telegram".files]
"tparser/telegram.py" = "2ed28ff9cdef5b1906baa8fca83a011e"
"tparser/packages.toml" = "be66af15a593176b1f495273c410ab99"

["packages/schedule".files]
"packages/schedule/main.py" = "81d8b8c01686f38fa10395c16d9f6a60"
"packages/schedule/packages.toml" = "8d59ff4dacaf7f0107d8a832c0727e10"
