["tparser/parser"]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "1.4.2"
build = 8
full_desc = "no full desc"
type = "package"
groups = []
authors = [ "Milinuri Nirvalen",]
require = []
used = [ "tparser/telegram", "packages/schedule",]
path = "./tparser"
multiple = true

["tparser/telegram"]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Telegram бот для tparser"
ver = "2.1 (SP v1.0)"
build = 5
authors = [ "Артём Березин",]
require = [ "tparser/parser",]
full_desc = "no full desc"
type = "package"
groups = []
used = []
path = "./tparser"
multiple = true

["packages/schedule"]
name = "schedule"
desc = "Получение школьного расписания в Чио"
ver = "SP v1.4"
build = 2
require = [ "tparser/parser",]
type = "plugin"
full_desc = "no full desc"
groups = []
authors = [ "Milinuri Nirvalen",]
used = []
path = "./packages/schedule"
multiple = false

["tparser/parser".files]
"tparser/tparser.py" = "fead64bfb7116e492afbbc1c021f3fa0"
"tparser/console.py" = "91688b7737fcdaf1a4792d7f8422e182"
"tparser/packages.toml" = "a98489fba68320c79f4cd06fa382ff00"

["tparser/telegram".files]
"tparser/telegram.py" = "f7192e65f3bd906da76c4817f150576d"
"tparser/packages.toml" = "a98489fba68320c79f4cd06fa382ff00"

["packages/schedule".files]
"packages/schedule/main.py" = "b6ae4497db9472237c574fcdf3741784"
"packages/schedule/packages.toml" = "ac14fcf34f13354f0e0a70f5555fd373"
