site_name: SPlatform
copyright: 2020 - 2024 Milinuri Nirvalen
repo_url: https://codeberg.org/salormoon/sparser
repo_name: Sparser
edit_uri: _edit/main/docs/

theme:
  name: material
  language: ru
  palette:
    scheme: slate
    primary: teal
    accent: teal
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.action.edit
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left


nav:
  - Home:
    - index.md
    - install.md
    - contribute.md
    - changelog.md
  - API:
    - sp/index.md
    - sp/counter.md
    - sp/utils.md
    - sp/version.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            parameter_headings: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docsting_style: "google"
            docstring_section_style: "list"
            merge_init_into_class: true
            show_if_no_docstring: true
            show_signature_annotations: true
            signature_crossrefs: true
            members_order: "source"

markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://codeberg.org/salormoon/
      name: Команда разработчиков проекта
    - icon: fontawesome/brands/telegram
      link: https://t.me/mili_qlaster
      name: Новостной канал проекта
