[tool.poetry]
name = "sp"
version = "5.3.6"
description = "School timetable parser."
authors = ["Milinuri Nirvalen <pentergust@mail.ru>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
loguru = "^0.7.0"
ujson = "^5.7.0"

[tool.poetry.group.dev.dependencies]
icecream = "^2.1.3"

[tool.poetry.group.telegram.dependencies]
aiogram = "^2.25.1"
gotify = "^0.5.0"

[tool.poetry.group.vk.dependencies]
vkbottle = "^4.3.12"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
