
# main -----------------------------------------------------------------

[tool.poetry]
name = "sp"
version = "6.0"
description = "School timetable parser."
authors = ["Milinuri Nirvalen <pentergust@mail.ru>"]
license = "GPL-3.0-or-later"
readme = ["README.md", "docs/index.rst"]
repository = "https://codeberg.org/Salormoon/Sparser"
documentation = "https://sparser.readthedocs.io/ru/latest/"


# Main depencies -------------------------------------------------------

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
loguru = "^0.7.0"
ujson = "^5.7.0"


# For dev depencies ----------------------------------------------------

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
icecream = "^2.1.3"
isort = "^5.13.2"
ruff = "^0.1.8"
mypy = "^1.8.0"


# For building docs ----------------------------------------------------

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-copybutton = "^0.5.2"
sphinx-book-theme = "^1.1.2"


# For Telegram Platform ------------------------------------------------

[tool.poetry.group.telegram]
optional = true

[tool.poetry.group.telegram.dependencies]
aiogram = "^3.2.0"
python-dotenv = "^1.0.0"


# Configure ruff -------------------------------------------------------

[tool.ruff]
line-length = 80
indent-width = 4

# Assume Python 3.8
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "I", "D", "N", "PL"]
ignore = ["D407", "D107", "D213", "D203"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
