[tool.poetry]
name = "sp"
version = "5.7"
description = "School timetable parser."
authors = ["Milinuri Nirvalen <pentergust@mail.ru>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
loguru = "^0.7.0"
ujson = "^5.7.0"

[tool.poetry.group.dev.dependencies]
icecream = "^2.1.3"
isort = "^5.13.2"
ruff = "^0.1.8"
mypy = "^1.8.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
furo = "^2024.1.29"

[tool.poetry.group.telegram.dependencies]
aiogram = "^3.2.0"
python-dotenv = "^1.0.0"

[tool.ruff]
line-length = 80
indent-width = 4

# Assume Python 3.8
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F", "I", "D", "N", "PL"]
ignore = ["D407", "D107"]
unfixable = ["I"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
