[parser]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "1.4.2"
build = 8
files = ["tparser.py", "console.py"]

[telegram]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Telegram бот для tparser"
ver = "2.1 (SP v1.0)"
build = 5
authors = [ "Артём Березин"]
files = [ "telegram.py"]
require = [ "tparser/parser"]
