[parser]
name = "Schedule parser"
desc = "Парсер школьного расписания"
ver = "2.1"
build = 13
files = ["tparser.py", "console.py"]

[telegram]
name = "Telegram Schedule"
desc = "[pytelegrambotapi] Бот для отправки расписания уроков"
ver = "sp v1.0"
build = 5
authors = [ "Артём Березин"]
files = [ "telegram.py"]
require = [ "tparser/parser"]
